# Generated by Django 5.1.2 on 2024-10-29 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=1)),
                ('address', models.CharField(default='Unknown', max_length=50)),
                ('contact', models.CharField(default='0000000000', max_length=12)),
                ('designation', models.CharField(default='Unknown', max_length=50)),
                ('specialization', models.CharField(default='General Practitioner', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(default=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=1)),
                ('address', models.CharField(default='Unknown', max_length=50)),
                ('weight', models.IntegerField(default=0)),
                ('blood_type', models.CharField(default='Unknown', max_length=30)),
                ('next_of_kin', models.CharField(default='Unknown', max_length=50)),
                ('kin_contact', models.CharField(default='', max_length=12)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_date', models.DateField(default=True)),
                ('temperature', models.CharField(default='Normal', max_length=20)),
                ('blood_pressure', models.CharField(default='120/80', max_length=20)),
                ('disease', models.CharField(default='Unknown', max_length=50)),
                ('remarks', models.CharField(default='None', max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateField(default=True)),
                ('name', models.CharField(default='General Treatment', max_length=50)),
                ('prescription', models.TextField(default='None', max_length=100)),
                ('recommendations', models.CharField(default='None', max_length=50)),
                ('amount_to_be_paid', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('C', 'CLEARED'), ('U', 'UNPAID')], default='U', max_length=1, null=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhospital.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=True)),
                ('amount_paid', models.IntegerField(default=0)),
                ('received_by', models.CharField(default='Unknown', max_length=50)),
                ('payment_method', models.CharField(default='Unknown', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhospital.patient')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhospital.treatment')),
            ],
        ),
    ]
