# Generated by Django 5.1.2 on 2024-10-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhospital', '0002_alter_diagnosis_diagnosis_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
