# Generated by Django 5.1.2 on 2024-11-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhospital', '0005_alter_patient_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(choices=[('O', 'O'), ('A', 'A'), ('B', 'B'), ('B+', 'B+'), ('A+', 'A+')], default='0', max_length=2),
        ),
    ]
