# Generated by Django 5.1.2 on 2024-11-08 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhospital', '0006_alter_patient_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myhospital.doctor'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myhospital.patient'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myhospital.patient'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='treatment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myhospital.treatment'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='diagnosis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myhospital.diagnosis'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='recommendations',
            field=models.CharField(max_length=40),
        ),
    ]
