# Generated by Django 5.1.2 on 2024-11-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhospital', '0007_alter_diagnosis_doctor_alter_diagnosis_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CREDIT CARD', 'CREDIT CARD'), ('MASTER CARD', 'MASTER CARD'), ('PAY PAL', 'PAY PAL'), ('MOBILE MONEY', 'MOBILE MONE')], max_length=50),
        ),
    ]
