# Generated by Django 5.1.2 on 2024-11-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhospital', '0008_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CREDIT CARD', 'CREDIT CARD'), ('MASTER CARD', 'MASTER CARD'), ('PAY PAL', 'PAY PAL'), ('MOBILE MONEY', 'MOBILE MONEY'), ('BANK TRANSFER', 'BANK TRANSFER')], default='CASH', max_length=50),
        ),
    ]
